object Versions {
    const val arrow = "0.13.2"
    const val assertj = "3.20.2"
    const val commonsCodec = "1.15"
    const val commonsDbcp2 = "2.8.0"
    const val commonsLang3 = "3.12.0"
    const val commonsPool2 = "2.10.0"
    const val commonsText = "1.9"
    const val gradle = "7.1.1"
    const val jackson = "2.12.4"
    const val jooq = "3.15.0"
    const val junit = "5.7.2"
    const val kotest = "4.6.0"
    const val kotestExtensionsSpring = "4.4.3"
    const val kotlin = "1.5.21"
    const val kotlinCoroutines = "1.5.0"
    const val logback = "1.2.3"
    const val mockito = "3.11.2"
    const val pemKeystore = "2.2.0"
    const val postgresql = "42.2.23"
    const val slf4j = "1.7.31"
    const val springBoot = "2.5.2"
    const val springDependencyManagement = "1.0.11.RELEASE"
    const val typesafeConfig = "1.4.1"
}